name: Ellis resume

on:
  push:
    branches: [ main ]
    paths:
    - webfrontend/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SECRET }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az storage blob upload-batch --account-name astroworld -d '$web' -s webfrontend/
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az cdn endpoint purge --content-paths  "/*" --profile-name "Drift" --name "spaceship" --resource-group "greenastro"

  # Azure logout
    - name: logout
      run: |
        az logout
